config/routes.rb
Rails.application.routes.draw do

  root "lists#index"

  resources :lists do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 5 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :title, :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @movie = Movie.find(params[:bookmark][:movie_id])
    @bookmark = Bookmark.new(list: @list, movie: @movie, comment: params[:bookmark][:comment])

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save

    redirect_to list_path(@list)
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container mt-5">
  <%= form_with model: Bookmark.new, url: list_bookmarks_path(@list), local: true do |f| %>
    <div>
      <%= f.label :movie_id, "Choose a movie" %>
      <%= f.collection_select :movie_id, Movie.all, :id, :title %>
    </div>
    <div>
      <%= f.label :comment %>
      <%= f.text_field :comment %>
    </div>
    <%= f.submit "Add Movie" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Edit</h1>

<div class="container">
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/index.html.erb
<img src="https://eloutput.com/wp-content/uploads/2022/06/sala-cine.jpg" class="custom-image" alt="photo">

<div class="container mt-3">
  <div class="d-flex justify-content-between align-items-center my-5 border-dark">
    <h1>My lists</h1>
    <%= link_to "Add a list", new_list_path, class: "btn btn-primary" %>
  </div>

  <div class="row gy-3 justify-content-center">
    <% @lists.each do |list| %>
    <div class="col-12 col-sm-6 col-lg-4">
      <div class="card mb-3" style="width: 18rem;">
        <% if list.photo.attached? %>
          <%= cl_image_tag list.photo.key, class: "card-img-top custom-card-img" %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= list.name %></h5>
          <div class="d-flex justify-content-between">
            <%= link_to 'Go', list_path(list), class: "btn btn-primary" %>
            <%= link_to 'Edit', edit_list_path(list), class: "btn btn-secondary" %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>New</h1>

<div class="container">
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<% if @list.photo.attached? %>
  <%= cl_image_tag @list.photo.key, class: "custom-image" %>
<% end %>

<h1><%= @list.name %></h1>

<div class="container">
  <div class="my-3">
    <%= link_to "Add a movie", new_list_bookmark_path(@list) %>
  </div>

  <div class="row g-3">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card col-4" style="width: 18rem;">
        <img src="<%= bookmark.movie.poster_url %>" class="card-img-top" alt="...">
        <div class="card-body">
          <h3 class="card-text"><%= bookmark.movie.title %></h3>
          <p class="card-text"><%= bookmark.movie.overview %></p>
          <%= link_to "Delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="my-3">
    <%= link_to "Back", lists_path %>
  </div>
</div>